### PR TITLE
Remove Papirus-Adapta{,-Nokto}-Maia icons. Add workaround for future versions of papirus-icon-theme

### PR DESCRIPTION
**Pull request by SmartFinn**
In the near future, Papirus-Adapta and Papirus-Adapa-Nokto will be removed from papirus-icon-theme PapirusDevelopmentTeam/papirus-icon-theme#1499. To avoid breaking icon theme for end users that update papirus-icon-theme from git I recommend adding the workaround first.

Tested on Manjaro KDE 17.1.12 and Manjaro GNOME 17.1.12.

### CODE REVIEW

**Comment by Ste74** [comment]
@SmartFinn you mean this work if i build papirus-icons-theme from git or also with the current release of the theme? I can do right now?

**Comment by SmartFinn** [comment]
@Ste74 yes, merge this now, please. After merging this branch [papirus-icon-theme/remove-adapta](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/tree/remove-adapta) the themes will be removed. That is may break the Papirus-Adapta{,-Nokto}-Maia themes for users that use `papirus-icon-theme-git` package or our installation script.

**Comment by SmartFinn** [comment]
After merging Papirus-Adapta-Maia will be used Papirus-Maia icons. Papirus-Adapa-Nokto-Maia will be used Papirus-Dark-Maia icons.

**Comment by Ste74** [comment]
Ok, thank you for explaination and thank you again for your work :wink:

**Pull request merged**
